### PR TITLE
Disable process crash reports by default

### LINKED ISSUE #179: Get rid of 'crash' logs in AtomVM
AtomVM logs a 'crash' error whenever a process exits with a reason other than `:normal`, `:shutdown`, or `{:shutdown, reason}`. While these logs are helpful, they can be false positives, for example, the Elixir compiler's internal processes exit with different reasons when compiling modules, even if everything's fine.

This needs to wait until #178, so that we have some logs when processes actually crash.

### PR DESCRIPTION
**Pull request by mat-hek**
blocked by https://github.com/software-mansion/popcorn/issues/178
closes https://github.com/software-mansion/popcorn/issues/179

These changes are made under both the "Apache 2.0" and the "GNU Lesser General
Public License 2.1 or later" license terms (dual license).

SPDX-License-Identifier: Apache-2.0 OR LGPL-2.1-or-later

### CODE REVIEW

File: src/libAtomVM/process_crash_report.c [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+            fprintf(stderr, "<");
+        }
+        fprintf(stderr, "---> ");
+        term_display(stderr, term_from_local_process_id(ctx->process_id), ctx);
+        fprintf(stderr, "\n");
+    }
+    synclist_unlock(&ctx->global->processes_table);
+    fprintf(stderr, "\n\n**End Of Crash Report**\n");
+}
+#endif
```
Comment (FranekKubis) [inline src/libAtomVM/process_crash_report.c]: format

**Review by jgonet — APPROVED** [review]

File: src/libAtomVM/process_crash_report.c (hunk 1 above)
Comment (mat-hek) [reply src/libAtomVM/process_crash_report.c]: Do you mean the code formatting? I formatted it with `clang-format`

Comment (FranekKubis) [reply src/libAtomVM/process_crash_report.c]: I thought it should do the newline at the end of the file, but if you checked it tahts ok for me.

**Review by FranekKubis — APPROVED** [review]

File: src/libAtomVM/process_crash_report.c (hunk 1 above)
Comment (mat-hek) [reply src/libAtomVM/process_crash_report.c]: Apparently it doesn't, added manually
